### ISSUE TITLE
nglview 

### ISSUE THREAD

**Issue by shahik** [salesforce/provis#3]
Hi, 
     nglview is problematic how can I save the resulting PDB structure from the notebook example? Any code directions? 
Greetings!

**Comment by jessevig** [comment]
Hi @shahik what type of file did you want to save? If you want to save an image file, you can issue a command like this, once you've arranged the protein to your liking: `view2.download_image(filename="testing.png")` Are you able to get to the point of rendering the protein in the notebook. Also note that we will be releasing an update in the coming weeks and update the nglview instructions.

**Comment by shahik** [comment]
thanks for coming back an update would be great as I am using colab and nglview does not render/work on colab yet.
