### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by AalaaNagy88** [salesforce/provis#5]
Hi,
we are professional master's students at Ottawa University. we want to use your paper as a benchmark for our graduation project.
We want to replicate your paper as a step in our graduation project.
But while running the code we get a **403 Forbidden**  while we try to download the dataset.
at this line : wget http://s3.amazonaws.com/proteindata/data_pytorch/secondary_structure.tar.gz

**Comment by alibekk93** [comment]
Hey, I am not sure if it is the same file, but maybe it will work? It's a PDB file with secondary structures in FASTA

https://cdn.rcsb.org/etl/kabschSander/ss.txt.gz

Btw I am also from uOttawa, what lab are you guys?

**Comment by AalaaNagy88** [comment]
Thank you.
 we will try to run with this dataset. We are students from Egypt who study online.
Could you give us your linkedIn account?

**Comment by jessevig** [comment]
Hello, apologies for the delayed response. I have changed the dataset links in the README to the updated versions from the TAPE repository.

**Comment by Moeinh77** [comment]
Hi, how can I run the experiments with a custom dataset of my own?
