### ISSUE TITLE
Some problems related to AMINO ACIDS partial

### ISSUE THREAD

**Issue by Carrotljw** [salesforce/provis#6]
Hi, This work is very interesting, I encountered some doubts in the process of reading the article, I hope to get your help
In the paper section 4.4: Attention heads specialize in particular amino acids
I don't know how this matrix is calculated, and  I didn't find the corresponding calculation part. Could you tell me where the calculation formula and code are located? Hope to get your reply, thank you very much, have a good life😁

**Comment by Carrotljw** [comment]
![image](https://user-images.githubusercontent.com/34529082/170913568-f22a2ccf-57d6-4407-a1c0-48e636a7e29b.png)
Is it the case of properties of individual tokens, f(i, j) to return 1 if the property is present in token j (if j is a specific amino acid, for example, when calculating pro, j is the amino acid of pro) Looking forward to your reply~Thank you

**Comment by jessevig** [comment]
Hi @Carrotljw, apologies for the delay in responding. 

Yes, your interpretation above is correct. The code for this is invoked as follows:

https://github.com/salesforce/provis/blob/master/protein_attention/attention_analysis/scripts/compute_all_features_tape_bert.sh executes the following step:

```
python compute_edge_features.py  \
 --exp-name edge_features_aa_tape_bert \
 --features aa \
 --dataset proteinnet \
 --num-sequences 5000 \
 --max-seq-len 512 \
 --min-attn .3 \
 --shuffle
```

Given the `--features aa` argument, the following code is invoked in `compute_edge_features`: 

```
        if feature_name == 'aa':
            features.append(AminoAcidFeature())
```

This will then result in the mentioned matrix getting computed. However, the underlying computation (described by you) is fairly simple, so it may be easier to implement it yourself as a standalone. Let me know if you have any questions.

Best,
Jesse

**Comment by Carrotljw** [comment]
Got it!😁Thanks for your reply.
Best!
